### ISSUE TITLE
Project webpage

### ISSUE THREAD

**Issue by jamesxiang11** [baurls/Covid-19-Visualization#1]
Hey there,

I am a fresh mater's student at Umass and was enrolled in this class for this spring. Is it possible to share the webpage version to me? I didn't find it in the folder. I wanted to get a sense of how complicated/innovative the project needs to be. Expectations seem to be very high. Thanks in advance!

**Comment by baurls** [comment]
The Code here is the actual Web-Version. 
By starting the python script, you set up a server (localhost here) that hosts the website dynamically.
So if you want to see the web version, just clone the repo and run the server.

There's so running server online so far.
